os:
  - linux

dist: xenial

language: python

python:
  - 3.6

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install codecov

script:
  - python -m pytest -v

after_success:
  - pytest --cov=./
  - codecov

deploy:
  provider: elasticbeanstalk
  wait_until_deployed: true
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_ACCESS_KEY_SECRET"
  region: "$AWS_REGION"
  app: "$AWS_EB_APPLICATION"
  env: "$AWS_EB_ENVIRONMENT"
  bucket_name: "$AWS_EB_S3_BUCKET"
  on:
    branch: main
